# Generated by Django 4.1.4 on 2024-03-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TitleText', models.CharField(help_text='Enter Big Text', max_length=2000)),
                ('SubtitleText', models.CharField(help_text='Enter Sub Text', max_length=1000)),
                ('CoverPhoto', models.ImageField(help_text='Upload Cover Photo To Be Used As Background Of Home Page', upload_to='uploadedMedia/')),
            ],
        ),
    ]
