# Generated by Django 4.1.4 on 2024-03-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='CoverPhoto',
            new_name='Cover_Photo',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='SubtitleText',
            new_name='Subtitle_Text',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='TitleText',
            new_name='Title_Text',
        ),
    ]
