# Generated by Django 4.1.4 on 2024-03-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_coverphoto_homepage_cover_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Has_Title', models.BooleanField(default=True)),
                ('Title_Text', models.CharField(help_text='Title of page (If Applicable)', max_length=2000)),
                ('Content', models.CharField(max_length=1000000)),
            ],
        ),
    ]
