# Generated by Django 4.1.4 on 2024-03-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='Category',
            field=models.CharField(choices=[('about', 'About'), ('meet_team', 'Meet The Team'), ('meet_research', 'Meet The Researchers'), ('research', 'Researches')], default='about', max_length=1000000),
        ),
    ]
