# Generated by Django 4.1.4 on 2024-03-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_page_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Social_Media', models.CharField(choices=[('fa-facebook', 'Facebook'), ('fa-youtube', 'Youtube'), ('fa-instagram', 'Instagram'), ('fa-twitter', 'Twitter'), ('fa-linkedin', 'Linkedin')], default='fa-instagram', max_length=1000000)),
                ('Social_Media_Link', models.CharField(help_text='Link to social media profile', max_length=2000)),
            ],
        ),
    ]
