# Generated by Django 4.1.4 on 2024-03-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=2000)),
                ('Email', models.EmailField(max_length=2000)),
                ('Phone_Number', models.CharField(help_text="Phone Number in this format: +971501234567 or type N/A if you don't want to show number", max_length=20)),
                ('Position', models.CharField(choices=[('Head', 'Head'), ('Junior Head', 'Junior Head')], max_length=2000)),
            ],
        ),
    ]
